title: "Randson"
email: "orandson@gmail.com"
bio: "Software Engineer"
summary: Software Engineer with more than 10 years of experience.

timezone: Europe/Lisbon

base_uri: "/"
base_url: "https://rands0n.com"

excerpt_separator: "<!--more-->"

# permalink
permalink: "/:title"

collections:
  talks:
    sort_by: when

# navigation
navs:
  - title: Blog
    url: "/blog"
  - title: Talks
    url: "/talks"
  - title: Vids
    url: "/vids"

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: development

# Build settings
markdown: kramdown
