version: "3"

services:
  app:
    build: .
    command: bundle exec jekyll serve -H 0.0.0.0 --livereload
    volumes:
      - ./:/app
      - bundle_path:/bundle
    environment:
      - BUNDLE_PATH=/bundle
    ports:
      - 4000:4000
      - 35729:35729

volumes:
  bundle_path:
